"""
Expande o seed de IDs para cobrir o canônico de Stardew Valley 1.6+
Fonte: https://eduanttunes.github.io/stardew_valley_ids/

Roda com: python scripts/expand-ids.py

Notas:
- string_id ficará null para entries novos (formato "(O)NN" requer mapeamento manual)
- preco_venda null para novos (apenas existentes já tinham)
- 22 categorias finais
"""
import json
from pathlib import Path

SEED = Path(__file__).parent.parent / "data" / "seed" / "ids.json"
existing = {e["codigo"]: e for e in json.loads(SEED.read_text(encoding="utf-8"))}


def add(codigo, nome, categoria, **kwargs):
    """Adiciona ou atualiza um ID. Preserva metadados existentes."""
    code = str(codigo)
    if code in existing:
        # mantém entry existente (já tem preço, string_id, etc)
        return
    existing[code] = {
        "nome": nome,
        "codigo": code,
        "string_id": kwargs.get("string_id"),
        "categoria": categoria,
        "descricao": kwargs.get("descricao"),
        "preco_venda": kwargs.get("preco_venda"),
        "fonte_obtencao": kwargs.get("fonte_obtencao"),
        "fonte_url": kwargs.get("fonte_url") or f"https://stardewvalleywiki.com/{nome.replace(' ', '_')}",
    }


# ============================================
# GEMAS & MINERAIS PRINCIPAIS
# ============================================
add(2, "Stone", "recurso")
add(60, "Emerald", "gema")
add(62, "Aquamarine", "gema")
add(64, "Ruby", "gema")
add(66, "Amethyst", "gema")
add(68, "Topaz", "gema")
add(70, "Jade", "gema")
add(72, "Diamond", "gema")
add(74, "Prismatic Shard", "gema")
add(80, "Quartz", "mineral")
add(82, "Fire Quartz", "mineral")
add(84, "Frozen Tear", "mineral")
add(86, "Earth Crystal", "mineral")

# ============================================
# FORRAGEIROS PRIMAVERA/VERAO/OUTONO/INVERNO
# ============================================
add(16, "Wild Horseradish", "forrageiro")
add(18, "Daffodil", "forrageiro")
add(20, "Leek", "forrageiro")
add(22, "Dandelion", "forrageiro")
add(78, "Cave Carrot", "forrageiro")
add(257, "Morel", "forrageiro")
add(259, "Fiddlehead Fern", "forrageiro")
add(281, "Chanterelle", "forrageiro")
add(283, "Holly", "forrageiro")
add(296, "Salmonberry", "forrageiro")
add(309, "Acorn", "forrageiro")
add(310, "Maple Seed", "forrageiro")
add(311, "Pine Cone", "forrageiro")
add(376, "Poppy", "forrageiro")
add(396, "Spice Berry", "forrageiro")
add(399, "Spring Onion", "forrageiro")
add(402, "Sweet Pea", "forrageiro")
add(404, "Common Mushroom", "forrageiro")
add(406, "Wild Plum", "forrageiro")
add(408, "Hazelnut", "forrageiro")
add(410, "Blackberry", "forrageiro")
add(412, "Winter Root", "forrageiro")
add(414, "Crystal Fruit", "forrageiro")
add(416, "Snow Yam", "forrageiro")
add(418, "Crocus", "forrageiro")
add(420, "Red Mushroom", "forrageiro")
add(422, "Purple Mushroom", "forrageiro")
add(430, "Truffle", "forrageiro")

# ============================================
# FRUTAS
# ============================================
add(88, "Coconut", "fruta")
add(90, "Cactus Fruit", "fruta")
add(91, "Banana", "fruta")
add(252, "Rhubarb", "fruta")
add(254, "Melon", "fruta")
add(258, "Blueberry", "fruta")
add(268, "Starfruit", "fruta")
add(282, "Cranberries", "fruta")
add(398, "Grape", "fruta")
add(400, "Strawberry", "fruta")
add(417, "Sweet Gem Berry", "fruta")
add(421, "Sunflower", "fruta")
add(454, "Ancient Fruit", "fruta")
add(613, "Apple", "fruta")
add(634, "Apricot", "fruta")
add(635, "Orange", "fruta")
add(636, "Peach", "fruta")
add(637, "Pomegranate", "fruta")
add(638, "Cherry", "fruta")
add(834, "Mango", "fruta")
add(889, "Qi Fruit", "fruta")

# ============================================
# VEGETAIS & CROPS
# ============================================
add(24, "Parsnip", "vegetal")
add(188, "Green Bean", "vegetal")
add(192, "Potato", "vegetal")
add(248, "Garlic", "vegetal")
add(250, "Kale", "vegetal")
add(256, "Tomato", "vegetal")
add(260, "Hot Pepper", "vegetal")
add(262, "Wheat", "vegetal")
add(264, "Radish", "vegetal")
add(266, "Red Cabbage", "vegetal")
add(270, "Corn", "vegetal")
add(271, "Unmilled Rice", "vegetal")
add(272, "Eggplant", "vegetal")
add(274, "Artichoke", "vegetal")
add(276, "Pumpkin", "vegetal")
add(278, "Bok Choy", "vegetal")
add(280, "Yam", "vegetal")
add(284, "Beet", "vegetal")
add(300, "Amaranth", "vegetal")
add(304, "Hops", "vegetal")
add(395, "Coffee Bean", "vegetal")
add(829, "Ginger", "vegetal")
add(830, "Taro Root", "vegetal")
add(890, "Qi Bean", "vegetal")

# ============================================
# PEIXES (Mines, oceano, rio, lago, Ginger Island)
# ============================================
add(128, "Pufferfish", "peixe")
add(129, "Anchovy", "peixe")
add(130, "Tuna", "peixe")
add(131, "Sardine", "peixe")
add(132, "Bream", "peixe")
add(136, "Largemouth Bass", "peixe")
add(137, "Smallmouth Bass", "peixe")
add(138, "Rainbow Trout", "peixe")
add(139, "Salmon", "peixe")
add(140, "Walleye", "peixe")
add(141, "Perch", "peixe")
add(142, "Carp", "peixe")
add(143, "Catfish", "peixe")
add(144, "Pike", "peixe")
add(145, "Sunfish", "peixe")
add(146, "Red Mullet", "peixe")
add(147, "Herring", "peixe")
add(148, "Eel", "peixe")
add(149, "Octopus", "peixe")
add(150, "Red Snapper", "peixe")
add(151, "Squid", "peixe")
add(152, "Seaweed", "peixe")
add(153, "Green Algae", "peixe")
add(154, "Sea Cucumber", "peixe")
add(155, "Super Cucumber", "peixe")
add(156, "Ghostfish", "peixe")
add(157, "White Algae", "peixe")
add(158, "Stonefish", "peixe")
add(159, "Crimsonfish", "peixe")
add(160, "Angler", "peixe")
add(161, "Ice Pip", "peixe")
add(162, "Lava Eel", "peixe")
add(163, "Legend", "peixe")
add(164, "Sandfish", "peixe")
add(165, "Scorpion Carp", "peixe")
add(269, "Midnight Carp", "peixe")
add(372, "Clam", "peixe")
add(397, "Sea Urchin", "peixe")
add(698, "Sturgeon", "peixe")
add(699, "Tiger Trout", "peixe")
add(700, "Bullhead", "peixe")
add(701, "Tilapia", "peixe")
add(702, "Chub", "peixe")
add(704, "Dorado", "peixe")
add(705, "Albacore", "peixe")
add(706, "Shad", "peixe")
add(707, "Lingcod", "peixe")
add(708, "Halibut", "peixe")
add(715, "Lobster", "peixe")
add(716, "Crayfish", "peixe")
add(717, "Crab", "peixe")
add(718, "Cockle", "peixe")
add(719, "Mussel", "peixe")
add(720, "Shrimp", "peixe")
add(721, "Snail", "peixe")
add(722, "Periwinkle", "peixe")
add(723, "Oyster", "peixe")
add(734, "Woodskip", "peixe")
add(775, "Glacierfish", "peixe")
add(795, "Void Salmon", "peixe")
add(796, "Slimejack", "peixe")
add(898, "Son of Crimsonfish", "peixe")
add(899, "Ms. Angler", "peixe")
add(900, "Legend II", "peixe")
add(901, "Radioactive Carp", "peixe")
add(902, "Glacierfish Jr.", "peixe")
add(682, "Mutant Carp", "peixe")

# ============================================
# SEMENTES & MUDAS
# ============================================
add(69, "Banana Sapling", "semente")
add(251, "Tea Sapling", "semente")
add(273, "Rice Shoot", "semente")
add(297, "Grass Starter", "semente")
add(299, "Amaranth Seeds", "semente")
add(301, "Grape Starter", "semente")
add(302, "Hops Starter", "semente")
add(347, "Rare Seed", "semente")
add(425, "Fairy Seeds", "semente")
add(427, "Tulip Bulb", "semente")
add(429, "Jazz Seeds", "semente")
add(431, "Sunflower Seeds", "semente")
add(433, "Coffee Bean (semente)", "semente")
add(453, "Poppy Seeds", "semente")
add(455, "Spangle Seeds", "semente")
add(472, "Parsnip Seeds", "semente")
add(473, "Bean Starter", "semente")
add(474, "Cauliflower Seeds", "semente")
add(475, "Potato Seeds", "semente")
add(476, "Garlic Seeds", "semente")
add(477, "Kale Seeds", "semente")
add(478, "Rhubarb Seeds", "semente")
add(479, "Melon Seeds", "semente")
add(480, "Tomato Seeds", "semente")
add(481, "Blueberry Seeds", "semente")
add(482, "Pepper Seeds", "semente")
add(483, "Wheat Seeds", "semente")
add(484, "Radish Seeds", "semente")
add(485, "Red Cabbage Seeds", "semente")
add(486, "Starfruit Seeds", "semente")
add(487, "Corn Seeds", "semente")
add(488, "Eggplant Seeds", "semente")
add(489, "Artichoke Seeds", "semente")
add(490, "Pumpkin Seeds", "semente")
add(491, "Bok Choy Seeds", "semente")
add(492, "Yam Seeds", "semente")
add(493, "Cranberry Seeds", "semente")
add(494, "Beet Seeds", "semente")
add(495, "Spring Seeds", "semente")
add(496, "Summer Seeds", "semente")
add(497, "Fall Seeds", "semente")
add(498, "Winter Seeds", "semente")
add(499, "Ancient Seeds", "semente")
add(628, "Cherry Sapling", "semente")
add(629, "Apricot Sapling", "semente")
add(630, "Orange Sapling", "semente")
add(631, "Peach Sapling", "semente")
add(632, "Pomegranate Sapling", "semente")
add(633, "Apple Sapling", "semente")
add(835, "Mango Sapling", "semente")
add(885, "Fiber Seeds", "semente")
add(891, "Mushroom Tree Seed", "semente")

# ============================================
# FLORES
# ============================================
add(591, "Tulip", "flor")
add(593, "Summer Spangle", "flor")
add(595, "Fairy Rose", "flor")
add(597, "Blue Jazz", "flor")

# ============================================
# ARTEFATOS
# ============================================
add(96, "Dwarf Scroll I", "artefato")
add(97, "Dwarf Scroll II", "artefato")
add(98, "Dwarf Scroll III", "artefato")
add(99, "Dwarf Scroll IV", "artefato")
add(100, "Chipped Amphora", "artefato")
add(101, "Arrowhead", "artefato")
add(103, "Ancient Doll", "artefato")
add(104, "Elvish Jewelry", "artefato")
add(105, "Chewing Stick", "artefato")
add(106, "Ornamental Fan", "artefato")
add(107, "Dinosaur Egg", "artefato")
add(108, "Rare Disc", "artefato")
add(109, "Ancient Sword", "artefato")
add(110, "Rusty Spoon", "artefato")
add(111, "Rusty Spur", "artefato")
add(112, "Rusty Cog", "artefato")
add(113, "Chicken Statue", "artefato")
add(114, "Ancient Seed", "artefato")
add(115, "Prehistoric Tool", "artefato")
add(116, "Dried Starfish", "artefato")
add(117, "Anchor", "artefato")
add(118, "Glass Shards", "artefato")
add(119, "Bone Flute", "artefato")
add(120, "Prehistoric Handaxe", "artefato")
add(121, "Dwarvish Helm", "artefato")
add(122, "Dwarf Gadget", "artefato")
add(123, "Ancient Drum", "artefato")
add(124, "Golden Mask", "artefato")
add(125, "Golden Relic", "artefato")
add(275, "Artifact Trove", "artefato")
add(392, "Nautilus Shell", "artefato")
add(393, "Coral", "artefato")
add(394, "Rainbow Shell", "artefato")

# ============================================
# FOSSEIS (Ginger Island Dig Site)
# ============================================
add(579, "Prehistoric Scapula", "fossil")
add(580, "Prehistoric Tibia", "fossil")
add(581, "Prehistoric Skull", "fossil")
add(582, "Skeletal Hand", "fossil")
add(583, "Prehistoric Rib", "fossil")
add(584, "Prehistoric Vertebra", "fossil")
add(585, "Skeletal Tail", "fossil")
add(586, "Nautilus Fossil", "fossil")
add(587, "Amphibian Fossil", "fossil")
add(588, "Palm Fossil", "fossil")
add(589, "Trilobite", "fossil")
add(820, "Fossilized Skull", "fossil")
add(821, "Fossilized Spine", "fossil")
add(822, "Fossilized Tail", "fossil")
add(823, "Fossilized Leg", "fossil")
add(824, "Fossilized Ribs", "fossil")
add(825, "Snake Skull", "fossil")
add(826, "Snake Vertebrae", "fossil")
add(827, "Mummified Bat", "fossil")
add(828, "Mummified Frog", "fossil")

# ============================================
# ARTISAN GOODS (mayo, queijo, wine, oil, cloth, mead)
# ============================================
add(174, "Large Egg (Branco)", "artisan")
add(176, "Egg (Branco)", "artisan")
add(180, "Egg (Marrom)", "artisan")
add(182, "Large Egg (Marrom)", "artisan")
add(184, "Milk", "artisan")
add(186, "Large Milk", "artisan")
add(289, "Ostrich Egg", "artisan")
add(303, "Pale Ale", "artisan")
add(306, "Mayonnaise", "artisan")
add(307, "Duck Mayonnaise", "artisan")
add(308, "Void Mayonnaise", "artisan")
add(340, "Honey", "artisan")
add(341, "Tea Set", "artisan")
add(342, "Pickles", "artisan")
add(344, "Jelly", "artisan")
add(346, "Beer", "artisan")
add(348, "Wine", "artisan")
add(350, "Juice", "artisan")
add(419, "Vinegar", "artisan")
add(423, "Rice", "artisan")
add(424, "Cheese", "artisan")
add(426, "Goat Cheese", "artisan")
add(428, "Cloth", "artisan")
add(440, "Wool", "artisan")
add(442, "Duck Egg", "artisan")
add(444, "Duck Feather", "artisan")
add(445, "Caviar", "artisan")
add(446, "Rabbit's Foot", "artisan")
add(459, "Mead", "artisan")
add(614, "Green Tea", "artisan")
add(724, "Maple Syrup", "artisan")
add(725, "Oak Resin", "artisan")
add(726, "Pine Tar", "artisan")
add(807, "Dinosaur Mayonnaise", "artisan")
add(812, "Roe", "artisan")
add(813, "Squid Ink", "artisan")
add(815, "Tea Leaves", "artisan")

# ============================================
# COOKED DISHES (artisan — pratos cozidos)
# ============================================
add(190, "Cauliflower (Vegetal)", "vegetal")
add(194, "Fried Egg", "artisan")
add(195, "Omelet", "artisan")
add(196, "Salad", "artisan")
add(197, "Cheese Cauliflower", "artisan")
add(198, "Baked Fish", "artisan")
add(199, "Parsnip Soup", "artisan")
add(200, "Vegetable Medley", "artisan")
add(201, "Complete Breakfast", "artisan")
add(202, "Fried Calamari", "artisan")
add(203, "Strange Bun", "artisan")
add(204, "Lucky Lunch", "artisan")
add(205, "Fried Mushroom", "artisan")
add(206, "Pizza", "artisan")
add(207, "Bean Hotpot", "artisan")
add(208, "Glazed Yams", "artisan")
add(209, "Carp Surprise", "artisan")
add(210, "Hashbrowns", "artisan")
add(211, "Pancakes", "artisan")
add(212, "Salmon Dinner", "artisan")
add(213, "Fish Taco", "artisan")
add(214, "Crispy Bass", "artisan")
add(215, "Pepper Poppers", "artisan")
add(216, "Bread", "artisan")
add(218, "Tom Kha Soup", "artisan")
add(219, "Trout Soup", "artisan")
add(220, "Chocolate Cake", "artisan")
add(221, "Pink Cake", "artisan")
add(222, "Rhubarb Pie", "artisan")
add(223, "Cookie", "artisan")
add(224, "Spaghetti", "artisan")
add(225, "Fried Eel", "artisan")
add(226, "Spicy Eel", "artisan")
add(227, "Sashimi", "artisan")
add(228, "Maki Roll", "artisan")
add(229, "Tortilla", "artisan")
add(230, "Red Plate", "artisan")
add(231, "Eggplant Parmesan", "artisan")
add(232, "Rice Pudding", "artisan")
add(233, "Ice Cream", "artisan")
add(234, "Blueberry Tart", "artisan")
add(235, "Autumn's Bounty", "artisan")
add(236, "Pumpkin Soup", "artisan")
add(237, "Super Meal", "artisan")
add(238, "Cranberry Sauce", "artisan")
add(239, "Stuffing", "artisan")
add(240, "Farmer's Lunch", "artisan")
add(241, "Survival Burger", "artisan")
add(242, "Dish O' The Sea", "artisan")
add(243, "Miner's Treat", "artisan")
add(244, "Roots Platter", "artisan")
add(265, "Seafoam Pudding", "artisan")
add(456, "Algae Soup", "artisan")
add(457, "Pale Broth", "artisan")
add(604, "Plum Pudding", "artisan")
add(605, "Artichoke Dip", "artisan")
add(606, "Stir Fry", "artisan")
add(607, "Roasted Hazelnuts", "artisan")
add(608, "Pumpkin Pie", "artisan")
add(609, "Radish Salad", "artisan")
add(610, "Fruit Salad", "artisan")
add(611, "Blackberry Cobbler", "artisan")
add(612, "Cranberry Candy", "artisan")
add(618, "Bruschetta", "artisan")
add(648, "Coleslaw", "artisan")
add(649, "Fiddlehead Risotto", "artisan")
add(651, "Poppyseed Muffin", "artisan")
add(727, "Chowder", "artisan")
add(728, "Fish Stew", "artisan")
add(729, "Escargot", "artisan")
add(730, "Lobster Bisque", "artisan")
add(731, "Maple Bar", "artisan")
add(732, "Crab Cakes", "artisan")
add(733, "Shrimp Cocktail", "artisan")
add(873, "Piña Colada", "artisan")
add(874, "Bug Steak", "artisan")
add(903, "Ginger Ale", "artisan")
add(904, "Banana Pudding", "artisan")
add(905, "Mango Sticky Rice", "artisan")
add(906, "Poi", "artisan")
add(907, "Tropical Curry", "artisan")
add(921, "Squid Ink Ravioli", "artisan")
add(243, "Miner's Treat", "artisan")
add(432, "Truffle Oil", "artisan")

# ============================================
# RECURSOS & MINERIOS
# ============================================
add(92, "Sap", "recurso")
add(93, "Torch", "recurso")
add(330, "Clay", "recurso")
add(378, "Copper Ore", "recurso")
add(380, "Iron Ore", "recurso")
add(382, "Coal", "recurso")
add(384, "Gold Ore", "recurso")
add(386, "Iridium Ore", "recurso")
add(388, "Wood", "recurso")
add(390, "Stone (mineração)", "recurso")
add(684, "Bug Meat", "recurso")
add(709, "Hardwood", "recurso")
add(766, "Slime", "recurso")
add(767, "Bat Wing", "recurso")
add(768, "Solar Essence", "recurso")
add(769, "Void Essence", "recurso")
add(771, "Fiber", "recurso")
add(805, "Tree Fertilizer", "recurso")
add(848, "Cinder Shard", "recurso")
add(852, "Dragon Tooth", "recurso")
add(872, "Fairy Dust", "recurso")
add(875, "Ectoplasm", "recurso")
add(881, "Bone Fragment", "recurso")
add(787, "Battery Pack", "recurso")
add(909, "Radioactive Ore", "recurso")

# ============================================
# BARRAS
# ============================================
add(334, "Copper Bar", "barra")
add(335, "Iron Bar", "barra")
add(336, "Gold Bar", "barra")
add(337, "Iridium Bar", "barra")
add(338, "Refined Quartz", "barra")
add(910, "Radioactive Bar", "barra")

# ============================================
# ANEIS
# ============================================
add(516, "Small Glow Ring", "anel")
add(517, "Glow Ring", "anel")
add(518, "Small Magnet Ring", "anel")
add(519, "Magnet Ring", "anel")
add(520, "Slime Charmer Ring", "anel")
add(521, "Warrior Ring", "anel")
add(522, "Vampire Ring", "anel")
add(523, "Savage Ring", "anel")
add(524, "Ring of Yoba", "anel")
add(525, "Sturdy Ring", "anel")
add(526, "Burglar's Ring", "anel")
add(527, "Iridium Band", "anel")
add(528, "Jukebox Ring", "anel")
add(529, "Amethyst Ring", "anel")
add(530, "Topaz Ring", "anel")
add(531, "Aquamarine Ring", "anel")
add(532, "Jade Ring", "anel")
add(533, "Emerald Ring", "anel")
add(534, "Ruby Ring", "anel")
add(839, "Thorns Ring", "anel")
add(861, "Protection Ring", "anel")
add(862, "Soul Sapper Ring", "anel")
add(863, "Phoenix Ring", "anel")
add(888, "Glowstone Ring", "anel")

# ============================================
# GEODOS
# ============================================
add(535, "Geode", "geodo")
add(536, "Frozen Geode", "geodo")
add(537, "Magma Geode", "geodo")
add(749, "Omni Geode", "geodo")

# ============================================
# MINERAIS (drops de geode)
# ============================================
add(538, "Alamite", "mineral")
add(539, "Bixite", "mineral")
add(540, "Baryte", "mineral")
add(541, "Aerinite", "mineral")
add(542, "Calcite", "mineral")
add(543, "Dolomite", "mineral")
add(544, "Esperite", "mineral")
add(545, "Fluorapatite", "mineral")
add(546, "Geminite", "mineral")
add(547, "Helvite", "mineral")
add(548, "Jamborite", "mineral")
add(549, "Jagoite", "mineral")
add(550, "Kyanite", "mineral")
add(551, "Lunarite", "mineral")
add(552, "Malachite", "mineral")
add(553, "Neptunite", "mineral")
add(554, "Lemon Stone", "mineral")
add(555, "Nekoite", "mineral")
add(556, "Orpiment", "mineral")
add(557, "Petrified Slime", "mineral")
add(558, "Thunder Egg", "mineral")
add(559, "Pyrite", "mineral")
add(560, "Ocean Stone", "mineral")
add(561, "Ghost Crystal", "mineral")
add(562, "Tigerseye", "mineral")
add(563, "Jasper", "mineral")
add(564, "Opal", "mineral")
add(565, "Fire Opal", "mineral")
add(566, "Celestine", "mineral")
add(567, "Marble", "mineral")
add(568, "Sandstone", "mineral")
add(569, "Granite", "mineral")
add(570, "Basalt", "mineral")
add(571, "Limestone", "mineral")
add(572, "Soapstone", "mineral")
add(573, "Hematite", "mineral")
add(574, "Mudstone", "mineral")
add(575, "Obsidian", "mineral")
add(576, "Slate", "mineral")
add(577, "Fairy Stone", "mineral")
add(578, "Star Shards", "mineral")

# ============================================
# SLIME EGGS
# ============================================
add(305, "Void Egg", "slime-egg")
add(413, "Blue Slime Egg", "slime-egg")
add(437, "Red Slime Egg", "slime-egg")
add(439, "Purple Slime Egg", "slime-egg")
add(680, "Green Slime Egg", "slime-egg")
add(857, "Tiger Slime Egg", "slime-egg")
add(876, "Prismatic Jelly", "especial")

# ============================================
# EQUIPAMENTOS (sprinklers, tackles, bait, totems, crab pot)
# ============================================
add(463, "Drum Block", "equipamento")
add(464, "Flute Block", "equipamento")
add(599, "Sprinkler", "equipamento")
add(621, "Quality Sprinkler", "equipamento")
add(645, "Iridium Sprinkler", "equipamento")
add(685, "Bait", "equipamento")
add(686, "Spinner", "equipamento")
add(687, "Dressed Spinner", "equipamento")
add(688, "Warp Totem: Farm", "equipamento")
add(689, "Warp Totem: Mountains", "equipamento")
add(690, "Warp Totem: Beach", "equipamento")
add(691, "Barbed Hook", "equipamento")
add(692, "Lead Bobber", "equipamento")
add(693, "Treasure Hunter", "equipamento")
add(694, "Trap Bobber", "equipamento")
add(695, "Cork Bobber", "equipamento")
add(703, "Magnet", "equipamento")
add(710, "Crab Pot", "equipamento")
add(774, "Wild Bait", "equipamento")
add(908, "Magic Bait", "equipamento")
add(913, "Enricher", "equipamento")
add(915, "Pressure Nozzle", "equipamento")
add(681, "Rain Totem", "equipamento")

# ============================================
# CONSTRUCAO (fences, floors, paths)
# ============================================
add(322, "Wood Fence", "construcao")
add(323, "Stone Fence", "construcao")
add(324, "Iron Fence", "construcao")
add(325, "Gate", "construcao")
add(328, "Wood Floor", "construcao")
add(329, "Stone Floor", "construcao")
add(298, "Hardwood Fence", "construcao")
add(331, "Weathered Floor", "construcao")
add(333, "Crystal Floor", "construcao")
add(401, "Straw Floor", "construcao")
add(405, "Wood Path", "construcao")
add(407, "Gravel Path", "construcao")
add(409, "Crystal Path", "construcao")
add(411, "Cobblestone Path", "construcao")
add(415, "Stepping Stone Path", "construcao")

# ============================================
# FERTILIZANTES & SOLOS
# ============================================
add(368, "Basic Fertilizer", "fertilizante")
add(369, "Quality Fertilizer", "fertilizante")
add(370, "Basic Retaining Soil", "fertilizante")
add(371, "Quality Retaining Soil", "fertilizante")
add(465, "Speed-Gro", "fertilizante")
add(466, "Deluxe Speed-Gro", "fertilizante")
add(918, "Hyper Speed-Gro", "fertilizante")
add(919, "Deluxe Fertilizer", "fertilizante")
add(920, "Deluxe Retaining Soil", "fertilizante")

# ============================================
# LIXO (importante pra Linus Special Order)
# ============================================
add(168, "Trash", "lixo")
add(169, "Driftwood", "lixo")
add(170, "Broken Glasses", "lixo")
add(171, "Broken CD", "lixo")
add(172, "Soggy Newspaper", "lixo")
add(747, "Rotten Plant", "lixo")

# ============================================
# ESPECIAL (Stardrop, Shorts, troféus, gemas Qi)
# ============================================
add(166, "Treasure Chest", "especial")
add(167, "Joja Cola", "especial")
add(277, "Wilted Bouquet", "especial")
add(326, "Dwarvish Translation Guide", "especial")
add(373, "Golden Pumpkin", "especial")
add(434, "Stardrop", "especial")
add(458, "Bouquet", "especial")
add(460, "Mermaid's Pendant", "especial")
add(468, "Stardew Hero Trophy", "especial")
add(746, "Jack-O-Lantern", "especial")
add(772, "Oil of Garlic", "artisan")
add(773, "Life Elixir", "especial")
add(789, "Lucky Purple Shorts", "especial")
add(791, "Golden Coconut", "especial")
add(858, "Qi Gem", "especial")
add(896, "Galaxy Soul", "especial")

# ============================================
# TEMPERO
# ============================================
add(917, "Qi Seasoning", "tempero")

# ============================================
# Salvar
# ============================================
out = sorted(existing.values(), key=lambda e: int(e["codigo"]) if e["codigo"].isdigit() else 0)
SEED.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

print(f"OK — total: {len(out)} IDs")

from collections import Counter
counter = Counter(e["categoria"] for e in out)
print("\nPor categoria:")
for cat, n in counter.most_common():
    print(f"  {cat}: {n}")
