import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const translations = {
  // Recursos
  "Stone": "Pedra",
  "Sap": "Seiva",
  "Torch": "Tocha",
  "Wood": "Madeira",
  "Hardwood": "Madeira Dura",
  "Coal": "Carvão",
  "Fiber": "Fibra",
  "Clay": "Argila",

  // Minérios e Barras
  "Copper Ore": "Minério de Cobre",
  "Iron Ore": "Minério de Ferro",
  "Gold Ore": "Minério de Ouro",
  "Iridium Ore": "Minério de Irídio",
  "Radioactive Ore": "Minério Radioativo",
  "Copper Bar": "Barra de Cobre",
  "Iron Bar": "Barra de Ferro",
  "Gold Bar": "Barra de Ouro",
  "Iridium Bar": "Barra de Irídio",
  "Radioactive Bar": "Barra Radioativa",
  "Refined Quartz": "Quartzo Refinado",

  // Gemas
  "Emerald": "Esmeralda",
  "Aquamarine": "Água-marinha",
  "Ruby": "Rubi",
  "Amethyst": "Ametista",
  "Topaz": "Topázio",
  "Jade": "Jade",
  "Diamond": "Diamante",

  // Minerais
  "Quartz": "Quartzo",
  "Fire Quartz": "Quartzo de Fogo",
  "Frozen Tear": "Lágrima Congelada",
  "Earth Crystal": "Cristal da Terra",

  // Minerais de Geodos
  "Alamite": "Alamita",
  "Bixite": "Bixita",
  "Baryte": "Barita",
  "Aerinite": "Aerinita",
  "Calcite": "Calcita",
  "Dolomite": "Dolomita",
  "Esperite": "Esperita",
  "Fluorapatite": "Fluorapatita",
  "Geminite": "Geminita",
  "Helvite": "Helvita",
  "Jamborite": "Jamborita",
  "Jagoite": "Jagoita",
  "Kyanite": "Cianita",
  "Lunarite": "Lunarita",
  "Malachite": "Malaquita",
  "Neptunite": "Neptunita",
  "Lemon Stone": "Pedra Limão",
  "Nekoite": "Nekoita",
  "Orpiment": "Ouropimento",
  "Petrified Slime": "Gosma Petrificada",
  "Thunder Egg": "Ovo de Trovão",
  "Pyrite": "Pirita",
  "Ocean Stone": "Pedra do Oceano",
  "Ghost Crystal": "Cristal Fantasma",
  "Tigerseye": "Olho de Tigre",
  "Jasper": "Jaspe",
  "Opal": "Opala",
  "Fire Opal": "Opala de Fogo",
  "Celestine": "Celestita",
  "Marble": "Mármore",
  "Sandstone": "Arenito",
  "Granite": "Granito",
  "Basalt": "Basalto",
  "Limestone": "Calcário",
  "Soapstone": "Pedra-sabão",
  "Hematite": "Hematita",
  "Mudstone": "Argilito",
  "Obsidian": "Obsidiana",
  "Slate": "Ardósia",
  "Fairy Stone": "Pedra de Fada",
  "Star Shards": "Fragmentos Estelares",

  // Geodos
  "Geode": "Geodo",
  "Frozen Geode": "Geodo Congelado",
  "Magma Geode": "Geodo de Magma",
  "Omni Geode": "Omnigeodo",
  "Artifact Trove": "Depósito de Artefatos",

  // Forrageiros
  "Wild Horseradish": "Rabanete-selvagem",
  "Daffodil": "Narciso",
  "Leek": "Alho-poró",
  "Dandelion": "Dente-de-leão",
  "Cave Carrot": "Cenoura das Cavernas",
  "Red Mushroom": "Cogumelo Vermelho",
  "Purple Mushroom": "Cogumelo Roxo",
  "Morel": "Cogumelo Morel",
  "Coconut": "Coco",
  "Cactus Fruit": "Fruta de Cacto",
  "Banana": "Banana",
  "Common Mushroom": "Cogumelo Comum",
  "Winter Root": "Raiz de Inverno",
  "Crystal Fruit": "Fruta de Cristal",
  "Snow Yam": "Inhame de Neve",
  "Crocus": "Croco",
  "Holly": "Azevinho",
  "Nautilus Shell": "Concha de Náutilo",
  "Coral": "Coral",
  "Sea Urchin": "Ouriço-do-mar",
  "Rainbow Shell": "Concha Arco-íris",
  "Spice Berry": "Baga de Especiarias",
  "Wild Plum": "Ameixa Selvagem",
  "Hazelnut": "Avelã",
  "Blackberry": "Amora",
  "Sweet Pea": "Ervilha Doce",
  "Spring Onion": "Cebolinha",
  "Chanterelle": "Cantarelo",
  "Salmonberry": "Amora-salmão",
  "Fiddlehead Fern": "Samambaia Jovem",
  "Ginger": "Gengibre",
  "Taro Root": "Taro",
  "Mango": "Manga",

  // Vegetais
  "Parsnip": "Pastinaca",
  "Garlic": "Alho",
  "Potato": "Batata",
  "Kale": "Couve",
  "Rhubarb": "Ruibarbo",
  "Melon": "Melão",
  "Tomato": "Tomate",
  "Blueberry": "Mirtilo",
  "Hot Pepper": "Pimenta",
  "Wheat": "Trigo",
  "Radish": "Rabanete",
  "Red Cabbage": "Repolho Roxo",
  "Starfruit": "Carambola",
  "Corn": "Milho",
  "Eggplant": "Berinjela",
  "Artichoke": "Alcachofra",
  "Pumpkin": "Abóbora",
  "Bok Choy": "Bok Choy",
  "Yam": "Inhame",
  "Cranberries": "Oxicoco",
  "Beet": "Beterraba",
  "Green Bean": "Vagem Verde",
  "Cauliflower (Vegetal)": "Couve-flor (Vegetal)",
  "Unmilled Rice": "Arroz Não Processado",
  "Rice Shoot": "Muda de Arroz",
  "Amaranth": "Amaranto",
  "Hops": "Lúpulo",
  "Qi Fruit": "Fruta Qi",

  // Frutas
  "Strawberry": "Morango",
  "Grape": "Uva",
  "Sweet Gem Berry": "Baga Gema Doce",
  "Apricot": "Damasco",
  "Orange": "Laranja",
  "Peach": "Pêssego",
  "Pomegranate": "Romã",
  "Cherry": "Cereja",
  "Apple": "Maçã",
  "Ancient Fruit": "Fruta Ancestral",

  // Flores
  "Tulip": "Tulipa",
  "Summer Spangle": "Lantejoula de Verão",
  "Fairy Rose": "Rosa das Fadas",
  "Blue Jazz": "Jazz Azul",
  "Poppy": "Papoula",
  "Sunflower": "Girassol",

  // Peixes
  "Pufferfish": "Baiacu",
  "Anchovy": "Anchova",
  "Tuna": "Atum",
  "Sardine": "Sardinha",
  "Bream": "Brema",
  "Largemouth Bass": "Robalo de Boca Grande",
  "Smallmouth Bass": "Robalo de Boca Pequena",
  "Rainbow Trout": "Truta Arco-íris",
  "Salmon": "Salmão",
  "Walleye": "Perca-americana",
  "Perch": "Perca",
  "Carp": "Carpa",
  "Catfish": "Bagre",
  "Pike": "Lúcio",
  "Sunfish": "Peixe-sol",
  "Red Mullet": "Salmonete",
  "Herring": "Arenque",
  "Eel": "Enguia",
  "Octopus": "Polvo",
  "Red Snapper": "Vermelho Americano",
  "Squid": "Lula",
  "Seaweed": "Alga Marinha",
  "Green Algae": "Alga Verde",
  "Sea Cucumber": "Pepino-do-mar",
  "Super Cucumber": "Super Pepino-do-mar",
  "Ghostfish": "Peixe-fantasma",
  "White Algae": "Alga Branca",
  "Stonefish": "Peixe-pedra",
  "Crimsonfish": "Peixe Carmesim",
  "Angler": "Peixe-anjo",
  "Ice Pip": "Peixe do Gelo",
  "Lava Eel": "Enguia de Lava",
  "Legend": "Lenda",
  "Sandfish": "Peixe de Areia",
  "Scorpion Carp": "Carpa Escorpião",
  "Midnight Carp": "Carpa da Meia-noite",
  "Mutant Carp": "Carpa Mutante",
  "Dorado": "Dourado",
  "Albacore": "Albacora",
  "Shad": "Sável",
  "Lingcod": "Lingcod",
  "Halibut": "Halibute",
  "Sturgeon": "Esturjão",
  "Tiger Trout": "Truta Tigre",
  "Bullhead": "Bagre-cabeça-de-touro",
  "Tilapia": "Tilápia",
  "Chub": "Chub",
  "Woodskip": "Peixe-do-bosque",
  "Void Salmon": "Salmão do Vazio",
  "Slimejack": "Peixe-gosma",
  "Glacierfish": "Peixe-glacial",
  "Son of Crimsonfish": "Filho do Peixe Carmesim",
  "Ms. Angler": "Srta. Peixe-anjo",
  "Legend II": "Lenda II",
  "Radioactive Carp": "Carpa Radioativa",
  "Glacierfish Jr.": "Peixe-glacial Jr.",

  // Frutos do Mar (Crab Pot)
  "Lobster": "Lagosta",
  "Crayfish": "Lagostim",
  "Crab": "Caranguejo",
  "Cockle": "Berbigão",
  "Mussel": "Mexilhão",
  "Shrimp": "Camarão",
  "Snail": "Caracol",
  "Periwinkle": "Caramujo",
  "Oyster": "Ostra",
  "Clam": "Amêijoa",

  // Lixo
  "Trash": "Lixo",
  "Driftwood": "Madeira à Deriva",
  "Broken Glasses": "Óculos Quebrados",
  "Broken CD": "CD Quebrado",
  "Soggy Newspaper": "Jornal Encharcado",

  // Ovos e laticínios
  "Large Egg (Branco)": "Ovo Grande (Branco)",
  "Egg (Branco)": "Ovo (Branco)",
  "Egg (Marrom)": "Ovo (Marrom)",
  "Large Egg (Marrom)": "Ovo Grande (Marrom)",
  "Milk": "Leite",
  "Large Milk": "Leite Grande",
  "Void Egg": "Ovo do Vazio",
  "Duck Egg": "Ovo de Pato",
  "Ostrich Egg": "Ovo de Avestruz",

  // Produtos artesanais
  "Mayonnaise": "Maionese",
  "Duck Mayonnaise": "Maionese de Pato",
  "Void Mayonnaise": "Maionese do Vazio",
  "Dinosaur Mayonnaise": "Maionese de Dinossauro",
  "Pale Ale": "Cerveja Clara",
  "Beer": "Cerveja",
  "Honey": "Mel",
  "Wine": "Vinho",
  "Juice": "Suco",
  "Pickles": "Picles",
  "Jelly": "Geleia",
  "Mead": "Hidromel",
  "Cloth": "Tecido",
  "Truffle": "Trufa",
  "Truffle Oil": "Óleo de Trufa",
  "Wool": "Lã",
  "Caviar": "Caviar",
  "Duck Feather": "Pena de Pato",
  "Rabbit's Foot": "Pata de Coelho",
  "Cheese": "Queijo",
  "Goat Cheese": "Queijo de Cabra",
  "Maple Syrup": "Xarope de Bordo",
  "Oak Resin": "Resina de Carvalho",
  "Pine Tar": "Alcatrão de Pinho",
  "Vinegar": "Vinagre",
  "Oil of Garlic": "Óleo de Alho",
  "Tea Leaves": "Folhas de Chá",
  "Roe": "Ovas",
  "Squid Ink": "Tinta de Lula",
  "Fried Egg": "Ovo Frito",
  "Coffee": "Café",
  "Coffee Bean (semente)": "Grão de Café (semente)",
  "Rice": "Arroz",

  // Culinária
  "Omelet": "Omelete",
  "Salad": "Salada",
  "Cheese Cauliflower": "Couve-flor ao Queijo",
  "Baked Fish": "Peixe Assado",
  "Parsnip Soup": "Sopa de Pastinaca",
  "Vegetable Medley": "Mix de Legumes",
  "Complete Breakfast": "Café da Manhã Completo",
  "Fried Calamari": "Lula Frita",
  "Strange Bun": "Pãozinho Estranho",
  "Lucky Lunch": "Almoço da Sorte",
  "Fried Mushroom": "Cogumelo Frito",
  "Pizza": "Pizza",
  "Bean Hotpot": "Caldeirão de Feijão",
  "Glazed Yams": "Inhame Caramelado",
  "Carp Surprise": "Surpresa de Carpa",
  "Hashbrowns": "Batata Palha",
  "Pancakes": "Panquecas",
  "Salmon Dinner": "Jantar de Salmão",
  "Fish Taco": "Taco de Peixe",
  "Crispy Bass": "Robalo Crocante",
  "Pepper Poppers": "Pimentões Recheados",
  "Bread": "Pão",
  "Tom Kha Soup": "Sopa Tom Kha",
  "Trout Soup": "Sopa de Truta",
  "Chocolate Cake": "Bolo de Chocolate",
  "Pink Cake": "Bolo Rosa",
  "Rhubarb Pie": "Torta de Ruibarbo",
  "Cookie": "Biscoito",
  "Spaghetti": "Espaguete",
  "Fried Eel": "Enguia Frita",
  "Spicy Eel": "Enguia Picante",
  "Sashimi": "Sashimi",
  "Maki Roll": "Rolo Maki",
  "Tortilla": "Tortilha",
  "Red Plate": "Prato Vermelho",
  "Eggplant Parmesan": "Berinjela ao Parmesão",
  "Rice Pudding": "Arroz Doce",
  "Ice Cream": "Sorvete",
  "Blueberry Tart": "Torta de Mirtilo",
  "Autumn's Bounty": "Fartura do Outono",
  "Pumpkin Soup": "Sopa de Abóbora",
  "Super Meal": "Super Refeição",
  "Cranberry Sauce": "Molho de Oxicoco",
  "Stuffing": "Recheio",
  "Farmer's Lunch": "Almoço do Fazendeiro",
  "Survival Burger": "Hambúrguer da Sobrevivência",
  "Dish O' The Sea": "Prato do Mar",
  "Miner's Treat": "Guloseima do Minerador",
  "Roots Platter": "Prato de Raízes",
  "Seafoam Pudding": "Pudim de Espuma do Mar",
  "Plum Pudding": "Pudim de Ameixa",
  "Artichoke Dip": "Patê de Alcachofra",
  "Stir Fry": "Refogado",
  "Roasted Hazelnuts": "Avelãs Torradas",
  "Pumpkin Pie": "Torta de Abóbora",
  "Radish Salad": "Salada de Rabanete",
  "Fruit Salad": "Salada de Frutas",
  "Blackberry Cobbler": "Torta de Amora",
  "Cranberry Candy": "Doce de Oxicoco",
  "Green Tea": "Chá Verde",
  "Bruschetta": "Bruschetta",
  "Coleslaw": "Salada de Repolho",
  "Fiddlehead Risotto": "Risoto de Samambaia",
  "Poppyseed Muffin": "Muffin de Papoula",
  "Algae Soup": "Sopa de Alga",
  "Pale Broth": "Caldo Pálido",
  "Chowder": "Chowder",
  "Fish Stew": "Ensopado de Peixe",
  "Escargot": "Escargot",
  "Lobster Bisque": "Bisque de Lagosta",
  "Maple Bar": "Barra de Bordo",
  "Crab Cakes": "Bolinhos de Caranguejo",
  "Shrimp Cocktail": "Coquetel de Camarão",
  "Ginger Ale": "Ginger Ale",
  "Banana Pudding": "Pudim de Banana",
  "Mango Sticky Rice": "Arroz Pegajoso com Manga",
  "Poi": "Poi",
  "Tropical Curry": "Curry Tropical",
  "Squid Ink Ravioli": "Ravióli de Tinta de Lula",
  "Bug Steak": "Bife de Inseto",
  "Piña Colada": "Piña Colada",
  "PiÃ±a Colada": "Piña Colada",

  // Artefatos
  "Dwarf Scroll I": "Pergaminho Anão I",
  "Dwarf Scroll II": "Pergaminho Anão II",
  "Dwarf Scroll III": "Pergaminho Anão III",
  "Dwarf Scroll IV": "Pergaminho Anão IV",
  "Chipped Amphora": "Ânfora Lascada",
  "Arrowhead": "Ponta de Flecha",
  "Ancient Doll": "Boneca Antiga",
  "Elvish Jewelry": "Joia Élfica",
  "Chewing Stick": "Graveto de Mascar",
  "Ornamental Fan": "Leque Ornamental",
  "Dinosaur Egg": "Ovo de Dinossauro",
  "Rare Disc": "Disco Raro",
  "Ancient Sword": "Espada Antiga",
  "Rusty Spoon": "Colher Enferrujada",
  "Rusty Spur": "Espora Enferrujada",
  "Rusty Cog": "Engrenagem Enferrujada",
  "Chicken Statue": "Estátua de Frango",
  "Ancient Seed": "Semente Ancestral",
  "Prehistoric Tool": "Ferramenta Pré-histórica",
  "Dried Starfish": "Estrela-do-mar Seca",
  "Anchor": "Âncora",
  "Glass Shards": "Cacos de Vidro",
  "Bone Flute": "Flauta de Osso",
  "Prehistoric Handaxe": "Machado Pré-histórico",
  "Dwarvish Helm": "Elmo Anão",
  "Dwarf Gadget": "Gadget Anão",
  "Ancient Drum": "Tambor Antigo",
  "Golden Mask": "Máscara Dourada",
  "Golden Relic": "Relíquia Dourada",
  "Dwarvish Translation Guide": "Guia de Tradução Anão",

  // Fósseis
  "Prehistoric Scapula": "Escápula Pré-histórica",
  "Prehistoric Tibia": "Tíbia Pré-histórica",
  "Prehistoric Skull": "Crânio Pré-histórico",
  "Skeletal Hand": "Mão Esquelética",
  "Prehistoric Rib": "Costela Pré-histórica",
  "Prehistoric Vertebra": "Vértebra Pré-histórica",
  "Skeletal Tail": "Cauda Esquelética",
  "Nautilus Fossil": "Fóssil de Náutilo",
  "Amphibian Fossil": "Fóssil de Anfíbio",
  "Palm Fossil": "Fóssil de Palmeira",
  "Trilobite": "Trilobita",
  "Fossilized Skull": "Crânio Fossilizado",
  "Fossilized Spine": "Coluna Fossilizada",
  "Fossilized Tail": "Cauda Fossilizada",
  "Fossilized Leg": "Perna Fossilizada",
  "Fossilized Ribs": "Costelas Fossilizadas",
  "Snake Skull": "Crânio de Cobra",
  "Snake Vertebrae": "Vértebras de Cobra",
  "Mummified Bat": "Morcego Mumificado",
  "Mummified Frog": "Sapo Mumificado",

  // Especiais
  "Golden Walnut": "Noz Dourada",
  "Prismatic Shard": "Estilhaço Prismático",
  "Treasure Chest": "Baú do Tesouro",
  "Joja Cola": "Joja Cola",
  "Golden Pumpkin": "Abóbora Dourada",
  "Wilted Bouquet": "Buquê Murchado",
  "Magic Rock Candy": "Bala de Pedra Mágica",
  "Stardrop": "Stardrop",
  "Bouquet": "Buquê",
  "Mermaid's Pendant": "Pingente de Sereia",
  "Stardew Hero Trophy": "Troféu do Herói de Stardew",
  "Jack-O-Lantern": "Abóbora de Halloween",
  "Lucky Purple Shorts": "Shorts Roxos da Sorte",
  "Golden Coconut": "Coco Dourado",
  "Battery Pack": "Bateria",
  "Cinder Shard": "Estilhaço de Brasa",
  "Dragon Tooth": "Dente de Dragão",
  "Qi Gem": "Gema Qi",
  "Qi Seasoning": "Tempero Qi",
  "Qi Bean": "Feijão Qi",
  "Fairy Dust": "Pó de Fada",
  "Ectoplasm": "Ectoplasma",
  "Prismatic Jelly": "Geleia Prismática",
  "Bone Fragment": "Fragmento de Osso",
  "Galaxy Soul": "Alma da Galáxia",
  "Rotten Plant": "Planta Podre",

  // Monstros e Drops
  "Slime": "Gosma",
  "Bat Wing": "Asa de Morcego",
  "Solar Essence": "Essência Solar",
  "Void Essence": "Essência do Vazio",
  "Bug Meat": "Carne de Inseto",
  "Life Elixir": "Elixir da Vida",
  "Slime Charmer Ring": "Anel Encantador de Gosmas",

  // Ovos de Slime
  "Blue Slime Egg": "Ovo de Gosma Azul",
  "Red Slime Egg": "Ovo de Gosma Vermelha",
  "Purple Slime Egg": "Ovo de Gosma Roxa",
  "Green Slime Egg": "Ovo de Gosma Verde",
  "Tiger Slime Egg": "Ovo de Gosma Tigre",

  // Anéis
  "Small Glow Ring": "Anel de Brilho Pequeno",
  "Glow Ring": "Anel de Brilho",
  "Small Magnet Ring": "Anel Magnético Pequeno",
  "Magnet Ring": "Anel Magnético",
  "Warrior Ring": "Anel de Guerreiro",
  "Vampire Ring": "Anel de Vampiro",
  "Savage Ring": "Anel Selvagem",
  "Ring of Yoba": "Anel de Yoba",
  "Sturdy Ring": "Anel Sólido",
  "Burglar's Ring": "Anel do Ladrão",
  "Iridium Band": "Bracelete de Irídio",
  "Jukebox Ring": "Anel de Jukebox",
  "Amethyst Ring": "Anel de Ametista",
  "Topaz Ring": "Anel de Topázio",
  "Aquamarine Ring": "Anel de Água-marinha",
  "Jade Ring": "Anel de Jade",
  "Emerald Ring": "Anel de Esmeralda",
  "Ruby Ring": "Anel de Rubi",
  "Glowstone Ring": "Anel de Pedra Brilhante",
  "Thorns Ring": "Anel de Espinhos",
  "Protection Ring": "Anel de Proteção",
  "Soul Sapper Ring": "Anel Sugador de Almas",
  "Phoenix Ring": "Anel Fênix",

  // Sementes e Mudas
  "Banana Sapling": "Muda de Banana",
  "Tea Sapling": "Muda de Chá",
  "Mango Sapling": "Muda de Manga",
  "Cherry Sapling": "Muda de Cereja",
  "Apricot Sapling": "Muda de Damasco",
  "Orange Sapling": "Muda de Laranja",
  "Peach Sapling": "Muda de Pêssego",
  "Pomegranate Sapling": "Muda de Romã",
  "Apple Sapling": "Muda de Maçã",
  "Grass Starter": "Semente de Grama",
  "Acorn": "Bolota",
  "Maple Seed": "Semente de Bordo",
  "Pine Cone": "Pinha",
  "Rare Seed": "Semente Rara",
  "Fiber Seeds": "Sementes de Fibra",
  "Mushroom Tree Seed": "Semente de Árvore Cogumelo",
  "Speed-Gro": "Speed-Gro",
  "Deluxe Speed-Gro": "Speed-Gro Deluxe",
  "Hyper Speed-Gro": "Speed-Gro Ultra",
  "Basic Fertilizer": "Fertilizante Básico",
  "Quality Fertilizer": "Fertilizante de Qualidade",
  "Deluxe Fertilizer": "Fertilizante Deluxe",
  "Tree Fertilizer": "Fertilizante de Árvore",
  "Basic Retaining Soil": "Solo Retentor Básico",
  "Quality Retaining Soil": "Solo Retentor de Qualidade",
  "Deluxe Retaining Soil": "Solo Retentor Deluxe",
  "Parsnip Seeds": "Sementes de Pastinaca",
  "Bean Starter": "Semente de Vagem",
  "Cauliflower Seeds": "Sementes de Couve-flor",
  "Potato Seeds": "Sementes de Batata",
  "Garlic Seeds": "Sementes de Alho",
  "Kale Seeds": "Sementes de Couve",
  "Rhubarb Seeds": "Sementes de Ruibarbo",
  "Melon Seeds": "Sementes de Melão",
  "Tomato Seeds": "Sementes de Tomate",
  "Blueberry Seeds": "Sementes de Mirtilo",
  "Pepper Seeds": "Sementes de Pimenta",
  "Wheat Seeds": "Sementes de Trigo",
  "Radish Seeds": "Sementes de Rabanete",
  "Starfruit Seeds": "Sementes de Carambola",
  "Corn Seeds": "Sementes de Milho",
  "Eggplant Seeds": "Sementes de Berinjela",
  "Artichoke Seeds": "Sementes de Alcachofra",
  "Pumpkin Seeds": "Sementes de Abóbora",
  "Bok Choy Seeds": "Sementes de Bok Choy",
  "Yam Seeds": "Sementes de Inhame",
  "Cranberry Seeds": "Sementes de Oxicoco",
  "Beet Seeds": "Sementes de Beterraba",
  "Spring Seeds": "Sementes de Primavera",
  "Summer Seeds": "Sementes de Verão",
  "Fall Seeds": "Sementes de Outono",
  "Winter Seeds": "Sementes de Inverno",
  "Ancient Seeds": "Sementes Ancestrais",
  "Grape Starter": "Semente de Uva",
  "Hops Starter": "Semente de Lúpulo",
  "Amaranth Seeds": "Sementes de Amaranto",
  "Sunflower Seeds": "Sementes de Girassol",
  "Poppy Seeds": "Sementes de Papoula",
  "Fairy Seeds": "Sementes de Fada",
  "Tulip Bulb": "Bulbo de Tulipa",
  "Jazz Seeds": "Sementes de Jazz",
  "Spangle Seeds": "Sementes de Spangle",

  // Cercas e Pisos
  "Wood Fence": "Cerca de Madeira",
  "Stone Fence": "Cerca de Pedra",
  "Iron Fence": "Cerca de Ferro",
  "Hardwood Fence": "Cerca de Madeira Dura",
  "Gate": "Portão",
  "Wood Floor": "Piso de Madeira",
  "Stone Floor": "Piso de Pedra",
  "Weathered Floor": "Piso Envelhecido",
  "Crystal Floor": "Piso de Cristal",
  "Straw Floor": "Piso de Palha",
  "Wood Path": "Caminho de Madeira",
  "Gravel Path": "Caminho de Cascalho",
  "Crystal Path": "Caminho de Cristal",
  "Cobblestone Path": "Calçamento",
  "Stepping Stone Path": "Caminho de Pedras",

  // Ferramentas e Máquinas
  "Sprinkler": "Aspersor",
  "Quality Sprinkler": "Aspersor de Qualidade",
  "Iridium Sprinkler": "Aspersor de Irídio",
  "Enricher": "Enriquecedor",
  "Pressure Nozzle": "Bico de Pressão",
  "Crab Pot": "Armadilha de Caranguejo",
  "Drum Block": "Bloco de Tambor",
  "Flute Block": "Bloco de Flauta",
  "Tea Set": "Serviço de Chá",
  "Magnet": "Ímã",

  // Totens e Iscas
  "Rain Totem": "Totem de Chuva",
  "Warp Totem: Farm": "Totem: Fazenda",
  "Warp Totem: Mountains": "Totem: Montanhas",
  "Warp Totem: Beach": "Totem: Praia",
  "Bait": "Isca",
  "Wild Bait": "Isca Selvagem",
  "Magic Bait": "Isca Mágica",
  "Spinner": "Spinner",
  "Dressed Spinner": "Spinner Enfeitado",
  "Barbed Hook": "Anzol Farpado",
  "Lead Bobber": "Chumbada",
  "Treasure Hunter": "Caçador de Tesouros",
  "Trap Bobber": "Boia-armadilha",
  "Cork Bobber": "Boia de Cortiça",
};

const filePath = join(__dirname, '..', 'data', 'seed', 'ids.json');
const data = JSON.parse(readFileSync(filePath, 'utf-8'));

let translated = 0;
let notFound = [];

const updated = data.map(item => {
  const pt = translations[item.nome];
  if (pt) {
    translated++;
    return { ...item, nome: pt };
  } else {
    notFound.push(item.nome);
    return item;
  }
});

writeFileSync(filePath, JSON.stringify(updated, null, 2), 'utf-8');

console.log(`✓ Traduzidos: ${translated} itens`);
if (notFound.length > 0) {
  console.log(`⚠ Sem tradução (${notFound.length}): ${notFound.join(', ')}`);
}
